<?php
if (! defined( "BASEPATH" )) {
	exit( "No direct script access allowed" );
}
/**
 * !!! DO NOT EDIT MANUALLY !!!
 * This file contains a structured list of the database tables that have been used to create the basic CSD structures
 * for managing the tables themselves.
 * Do not edit this file manually otherwise there is a risk of incorrect functioning of the "create_new_functionality" sections.
 * "path" is the subfolder name. Eg "TestFunc", so the lib, model etc will be each in subdirectory of relative path
 * /application/controller/ajax_requests/TestFunc
 * /application/libraries/Test_Func
 * ecc
 *
 * library is the name of the library and the suffix of the class
 * /application/controller/ajax_requests/TestFunc/Main_TestFunc.php => class Main_testFunc
 *
 * Same for other vars model, ajax, view, view_assembler
 *
 * $used_tables["table_name"] => array(
 * "path" => "",
 * "class" => "",
 * "library" => "",
 * "model" => "",
 * "ajax" => "",
 * "view" => "",
 * "view_assembler" => "",
 * );
 *
 * !!! DO NOT EDIT MANUALLY !!!
 */
$used_tables = array (
		"test_tablef" => array (
				"path" => "",
				"class" => "",
				"library" => "",
				"model" => "",
				"ajax" => "",
				"view" => "",
				"view_assembler" => "" 
		) 
);

?>